In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_excel("df_merged_data_october_march_all.xlsx")

In [75]:
df

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],40000.0,100000.0,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",30000.0,95000.0,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",35000.0,90000.0,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",35000.0,90000.0,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",90000.0,145000.0,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
174899,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,NaN,NaN,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
174900,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,NaN,NaN,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
174901,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,NaN,NaN,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
174902,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,NaN,NaN,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
174903,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [76]:
# Значения названий вакансий
df["Название вакансии"].unique()

array(['Стажер-инженер по тестированию',
       'Разработчик приложений (Qt/Qml)', 'Системный аналитик (UX)', ...,
       'Frontend Developer (vue)', 'Senior Angular Developer (remote)',
       'Руководитель проекта по цифровой трансформации (проект "Электронная коммерция")'],
      dtype=object)

In [77]:
# количество уникальных значений 
df["Название вакансии"].nunique()

21501

In [78]:
# количество пропущенных значений по столбцам
df.isnull().sum()

Название вакансии          0
Ключевые навыки          317
Начальная зарплата     53741
Конечная зарплата      58690
График работы          29003
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            122244
dtype: int64

In [79]:
df['Начальная зарплата'].min()

70.0

In [80]:
df[df['Начальная зарплата'] == 70.0]

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
164463,Заместитель руководителя службы питания,Релевантный опыт работы от 3х лет. Знание прог...,70.0,100000.0,NaN,От 3 до 6 лет,Москва,Максима Хотелс,NaN

In [81]:
df['Начальная зарплата'].max()

800000.0

In [82]:
df["Требуемый опыт"].unique()

array(['Нет опыта', 'От 3 до 6 лет', 'От 1 года до 3 лет', 'Более 6 лет'],
      dtype=object)

In [83]:
df["Ключевые навыки"][0]

"['hardskils']"

In [84]:
print(df['График работы'].unique())
time_schedule = df['График работы'].unique()

['Сменный график' 'Полный день' 'Гибкий график' 'Вахтовый метод'
 'Удаленная работа' nan]

In [85]:
def fill_salary(row):
    start_salary = np.nan
    end_salary = np.nan
    
    if pd.isnull(row['Начальная зарплата']) or pd.isnull(row['Конечная зарплата']):
        if row['Требуемый опыт'] in ['от 3 лет до 6 лет', 'Более 6 лет']:
            start_salary = np.around(np.random.randint(80000, 100000) / 5000) * 5000
            end_salary = np.around(np.random.randint(100000, 250000) / 5000) * 5000
        elif row['Требуемый опыт'] in ['Нет опыта', 'От 3 до 6 лет']:
            start_salary = np.around(np.random.randint(20000, 50000) / 5000) * 5000
            end_salary = np.around(np.random.randint(80000, 100000) / 5000) * 5000
    
    return start_salary, end_salary

# Применяем функцию к датафрейму для заполнения начальной и конечной зарплаты
df[['Начальная зарплата', 'Конечная зарплата']] = df.apply(lambda row: fill_salary(row), axis=1, result_type='expand')

print(df)

                                        Название вакансии  \
0                          Стажер-инженер по тестированию
1                         Разработчик приложений (Qt/Qml)
2                                 Системный аналитик (UX)
3       Системный программист С/С++ (разработка ОС Авр...
4                             С++/Qt разработчик (Senior)
...                                                   ...
174899                 Системный программист (Aurora TEE)
174900            Бэкенд-разработчик на Scala в Вертикали
174901      Руководитель команды системных компонентов UI
174902                                 Разработчик C++ Qt
174903                     Аналитик 1С: УХ (казначейство)

                                          Ключевые навыки  Начальная зарплата  \
0                                           ['hardskils']                 NaN
1                        ['Sailfish', 'OS', 'Qt', 'VoIP']                 NaN
2       ['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...                 NaN
3                                ['Linux', 'Linux', '++']                 NaN
4       ['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...                 NaN
...                                                   ...                 ...
174899  Знакомство с архитектурой операционных систем....             35000.0
174900  На первом поговорим об опыте и общих вопросах ...             50000.0
174901  Опыт интеграции и создания пакетов RPM. Участи...             95000.0
174902  Опыт разработки на QT не менее 2х лет. Опыт ко...             25000.0
174903  Образование – высшее (техническое или экономич...                 NaN

        Конечная зарплата   График работы      Требуемый опыт   Город  \
0                     NaN  Сменный график           Нет опыта  Москва
1                     NaN  Сменный график       От 3 до 6 лет  Москва
2                     NaN     Полный день  От 1 года до 3 лет  Москва
3                     NaN     Полный день  От 1 года до 3 лет  Москва
4                     NaN   Гибкий график         Более 6 лет  Москва
...                   ...             ...                 ...     ...
174899            90000.0     Полный день       От 3 до 6 лет  Москва
174900            80000.0     Полный день       От 3 до 6 лет  Москва
174901           155000.0     Полный день         Более 6 лет  Москва
174902            90000.0   Гибкий график       От 3 до 6 лет  Москва
174903                NaN     Полный день  От 1 года до 3 лет  Москва

                        Работодатель  Unnamed: 0
0            Лаборатория Касперского         NaN
1       Открытая мобильная платформа         NaN
2       Открытая мобильная платформа         NaN
3       Открытая мобильная платформа         NaN
4                                М13         NaN
...                              ...         ...
174899  Открытая мобильная платформа         NaN
174900                        Яндекс         NaN
174901  Открытая мобильная платформа         NaN
174902                  Фирма Светец         NaN
174903                         СИГМА         NaN

[174904 rows x 9 columns]

In [86]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки          317
Начальная зарплата    137417
Конечная зарплата     137417
График работы          29003
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            122244
dtype: int64

In [87]:
# Функция для заполнения столбца "График работы" с пустыми значениями
def fill_work_schedule(row):
    if pd.isnull(row['График работы']):
        return np.random.choice(time_schedule)
    else:
        return row['График работы']

# Применяем функцию к датафрейму для заполнения столбца "График работы"
df['График работы'] = df.apply(fill_work_schedule, axis=1)

df

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],NaN,NaN,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",NaN,NaN,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",NaN,NaN,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
174899,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
174900,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,50000.0,80000.0,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
174901,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,95000.0,155000.0,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
174902,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,25000.0,90000.0,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
174903,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [88]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки          317
Начальная зарплата    137417
Конечная зарплата     137417
График работы           4841
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            122244
dtype: int64

In [89]:
df["График работы"].unique()

array(['Сменный график', 'Полный день', 'Гибкий график', 'Вахтовый метод',
       'Удаленная работа', nan], dtype=object)

In [90]:
df.dropna(subset=['График работы'])

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],NaN,NaN,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",NaN,NaN,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",NaN,NaN,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
174899,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
174900,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,50000.0,80000.0,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
174901,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,95000.0,155000.0,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
174902,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,25000.0,90000.0,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
174903,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [91]:
df = df.reset_index(drop=True)

In [92]:
df

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],NaN,NaN,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",NaN,NaN,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",NaN,NaN,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
174899,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
174900,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,50000.0,80000.0,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
174901,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,95000.0,155000.0,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
174902,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,25000.0,90000.0,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
174903,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [93]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки          317
Начальная зарплата    137417
Конечная зарплата     137417
График работы           4841
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            122244
dtype: int64

In [94]:
df = df.dropna(subset=['Ключевые навыки','График работы'])

# Обновляем индексы строк
df.reset_index(drop=True, inplace=True)
df

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],NaN,NaN,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",NaN,NaN,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",NaN,NaN,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
169761,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169762,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,50000.0,80000.0,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
169763,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,95000.0,155000.0,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169764,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,25000.0,90000.0,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169765,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [95]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки            0
Начальная зарплата    134966
Конечная зарплата     134966
График работы              0
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            117106
dtype: int64

In [96]:
df[['Начальная зарплата', 'Конечная зарплата']] = df.apply(lambda row: fill_salary(row), axis=1, result_type='expand')

df

C:\Users\User\AppData\Local\Temp\ipykernel_2768\2240532373.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Начальная зарплата', 'Конечная зарплата']] = df.apply(lambda row: fill_salary(row), axis=1, result_type='expand')

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],30000.0,85000.0,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",45000.0,85000.0,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",NaN,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",100000.0,235000.0,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
169761,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,NaN,NaN,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169762,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,NaN,NaN,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
169763,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,NaN,NaN,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169764,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,NaN,NaN,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169765,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,NaN,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [97]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки            0
Начальная зарплата    103487
Конечная зарплата     103487
График работы              0
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            117106
dtype: int64

In [98]:
# Вычисляем медианные значения для всех столбцов
median_values = df['Начальная зарплата'].median()

# Заполняем пропущенные значения медианными значениями
df['Начальная зарплата'].fillna(median_values, inplace=True)

# Выводим обновленный датафрейм
df

C:\Users\User\AppData\Local\Temp\ipykernel_2768\1897306943.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Начальная зарплата'].fillna(median_values, inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_2768\1897306943.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Начальная зарплата'].fillna(median_values, inplace=True)

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],30000.0,85000.0,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",45000.0,85000.0,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",35000.0,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",35000.0,NaN,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",100000.0,235000.0,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
169761,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,NaN,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169762,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,35000.0,NaN,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
169763,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,35000.0,NaN,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169764,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,35000.0,NaN,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169765,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,35000.0,NaN,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [99]:
# Вычисляем медианные значения для всех столбцов
median_values = df['Конечная зарплата'].median()

# Заполняем пропущенные значения медианными значениями
df['Конечная зарплата'].fillna(median_values, inplace=True)

# Выводим обновленный датафрейм
df

C:\Users\User\AppData\Local\Temp\ipykernel_2768\2973264357.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Конечная зарплата'].fillna(median_values, inplace=True)
C:\Users\User\AppData\Local\Temp\ipykernel_2768\2973264357.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Конечная зарплата'].fillna(median_values, inplace=True)

,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,Стажер-инженер по тестированию,['hardskils'],30000.0,85000.0,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,Разработчик приложений (Qt/Qml),"['Sailfish', 'OS', 'Qt', 'VoIP']",45000.0,85000.0,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,Системный аналитик (UX),"['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...",35000.0,90000.0,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,Системный программист С/С++ (разработка ОС Авр...,"['Linux', 'Linux', '++']",35000.0,90000.0,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,С++/Qt разработчик (Senior),"['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...",100000.0,235000.0,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...
169761,Системный программист (Aurora TEE),Знакомство с архитектурой операционных систем....,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169762,Бэкенд-разработчик на Scala в Вертикали,На первом поговорим об опыте и общих вопросах ...,35000.0,90000.0,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
169763,Руководитель команды системных компонентов UI,Опыт интеграции и создания пакетов RPM. Участи...,35000.0,90000.0,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169764,Разработчик C++ Qt,Опыт разработки на QT не менее 2х лет. Опыт ко...,35000.0,90000.0,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169765,Аналитик 1С: УХ (казначейство),Образование – высшее (техническое или экономич...,35000.0,90000.0,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [100]:
df.isnull().sum()

Название вакансии          0
Ключевые навыки            0
Начальная зарплата         0
Конечная зарплата          0
График работы              0
Требуемый опыт             0
Город                      0
Работодатель               0
Unnamed: 0            117106
dtype: int64

In [101]:
df.to_excel('C:/Users/User/Desktop/diploma/clear_dataframe_new.xlsx')

In [62]:
skills = df["Ключевые навыки"]
skills

0                                             ['hardskils']
1                          ['Sailfish', 'OS', 'Qt', 'VoIP']
2         ['Sailfish', 'Ubuntu', 'Touch', 'UBports', 'Ma...
3                                  ['Linux', 'Linux', '++']
4         ['Qt', 'QML', 'Qt', 'SQL', 'SQLite', '++', 'Li...
                                ...
169774    Знакомство с архитектурой операционных систем....
169775    На первом поговорим об опыте и общих вопросах ...
169776    Опыт интеграции и создания пакетов RPM. Участи...
169777    Опыт разработки на QT не менее 2х лет. Опыт ко...
169778    Образование – высшее (техническое или экономич...
Name: Ключевые навыки, Length: 169779, dtype: object

In [63]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize

df = pd.read_excel('clear_dataframe.xlsx')

# Применение регулярного выражения и токенизации к каждой строке
def process_text(text):
    processed_text = re.sub('<[^>]*>|[а-яё.,!?:\n</>()\d&\[\]\-]', '', text, flags=re.I)  # Добавлены символы '\d&\[\]\-'
    tokens = word_tokenize(processed_text)
    return tokens

# Применение функции к столбцу "Ключевые навыки"
df['Ключевые навыки'] = df['Ключевые навыки'].apply(process_text)

# Сохранение данных
df.to_excel('clear_tokenized_dataframe.xlsx', index=False)

<>:9: SyntaxWarning: invalid escape sequence '\d'
<>:9: SyntaxWarning: invalid escape sequence '\d'
C:\Users\User\AppData\Local\Temp\ipykernel_2768\2101055813.py:9: SyntaxWarning: invalid escape sequence '\d'
  processed_text = re.sub('<[^>]*>|[а-яё.,!?:\n</>()\d&\[\]\-]', '', text, flags=re.I)  # Добавлены символы '\d&\[\]\-'

In [64]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [65]:
df = pd.read_excel('clear_tokenized_dataframe.xlsx')
df

,Unnamed: 0.1,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,0,Стажер-инженер по тестированию,"[""'hardskils"", ""'""]",40000,95000,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,1,Разработчик приложений (Qt/Qml),"[""'Sailfish"", ""'"", ""'OS"", ""'"", ""'Qt"", ""'"", ""'V...",25000,85000,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,2,Системный аналитик (UX),"[""'Sailfish"", ""'"", ""'Ubuntu"", ""'"", ""'Touch"", ""...",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,3,Системный программист С/С++ (разработка ОС Авр...,"[""'Linux"", ""'"", ""'Linux"", ""'"", ""'++"", ""'""]",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,4,С++/Qt разработчик (Senior),"[""'Qt"", ""'"", ""'QML"", ""'"", ""'Qt"", ""'"", ""'SQL"", ...",90000,175000,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...,...
169774,169774,Системный программист (Aurora TEE),"['ARM', 'ARM', 'assembler', 'ARM', 'TrustZone']",35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169775,169775,Бэкенд-разработчик на Scala в Вертикали,[],35000,90000,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN
169776,169776,Руководитель команды системных компонентов UI,"['RPM', 'open', 'source', 'Sailfish', 'OS', 'A...",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169777,169777,Разработчик C++ Qt,['QT'],35000,90000,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169778,169778,Аналитик 1С: УХ (казначейство),"['–', '–']",35000,90000,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [66]:
# находим и удаляем все строки где навыков вообще нет
empty = df[df["Ключевые навыки"]=='[]']
empty

,Unnamed: 0.1,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
48804,48804,Системный администратор,[],30000,95000,Сменный график,От 3 до 6 лет,Москва,"ПОБЕДА, кондитерская фабрика",44.0
48834,48834,DevOps / Системный администратор (Кипр),[],30000,90000,Полный день,От 3 до 6 лет,Москва,АЙТИ.СПЕЙС,74.0
48872,48872,Инженер технической поддержки,[],45000,85000,Удаленная работа,От 3 до 6 лет,Москва,Открытая мобильная платформа,112.0
48905,48905,Специалист внедрения и техподдержки СОРМ,[],35000,90000,Гибкий график,От 1 года до 3 лет,Москва,СПЕЦИАЛЬНЫЕ ТЕХНОЛОГИИ,145.0
49079,49079,Ведущий инженер поддержки,[],35000,90000,Полный день,От 1 года до 3 лет,Москва,"ДИКСИ, группа компаний",319.0
...,...,...,...,...,...,...,...,...,...,...
169750,169750,Руководитель ИТ-проектов,[],35000,90000,Полный день,От 3 до 6 лет,Москва,Ростелеком,NaN
169754,169754,Руководитель проектов,[],35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169764,169764,Менеджер по продажам (B2B/B2G),[],35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169768,169768,Исследователь безопасности ОС,[],35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169775,169775,Бэкенд-разработчик на Scala в Вертикали,[],35000,90000,Полный день,От 3 до 6 лет,Москва,Яндекс,NaN

In [67]:
not_empty = df[df["Ключевые навыки"]!='[]']
not_empty

,Unnamed: 0.1,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,0,Стажер-инженер по тестированию,"[""'hardskils"", ""'""]",40000,95000,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,1,Разработчик приложений (Qt/Qml),"[""'Sailfish"", ""'"", ""'OS"", ""'"", ""'Qt"", ""'"", ""'V...",25000,85000,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,2,Системный аналитик (UX),"[""'Sailfish"", ""'"", ""'Ubuntu"", ""'"", ""'Touch"", ""...",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,3,Системный программист С/С++ (разработка ОС Авр...,"[""'Linux"", ""'"", ""'Linux"", ""'"", ""'++"", ""'""]",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,4,С++/Qt разработчик (Senior),"[""'Qt"", ""'"", ""'QML"", ""'"", ""'Qt"", ""'"", ""'SQL"", ...",90000,175000,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...,...
169773,169773,Начальник отдела развития и поддержки разработ...,"['Qt', 'C++', 'POSIX']",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169774,169774,Системный программист (Aurora TEE),"['ARM', 'ARM', 'assembler', 'ARM', 'TrustZone']",35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
169776,169776,Руководитель команды системных компонентов UI,"['RPM', 'open', 'source', 'Sailfish', 'OS', 'A...",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
169777,169777,Разработчик C++ Qt,['QT'],35000,90000,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
169778,169778,Аналитик 1С: УХ (казначейство),"['–', '–']",35000,90000,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [68]:
not_empty = not_empty.reset_index()
not_empty

,index,Unnamed: 0.1,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель,Unnamed: 0
0,0,0,Стажер-инженер по тестированию,"[""'hardskils"", ""'""]",40000,95000,Сменный график,Нет опыта,Москва,Лаборатория Касперского,NaN
1,1,1,Разработчик приложений (Qt/Qml),"[""'Sailfish"", ""'"", ""'OS"", ""'"", ""'Qt"", ""'"", ""'V...",25000,85000,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
2,2,2,Системный аналитик (UX),"[""'Sailfish"", ""'"", ""'Ubuntu"", ""'"", ""'Touch"", ""...",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
3,3,3,Системный программист С/С++ (разработка ОС Авр...,"[""'Linux"", ""'"", ""'Linux"", ""'"", ""'++"", ""'""]",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа,NaN
4,4,4,С++/Qt разработчик (Senior),"[""'Qt"", ""'"", ""'QML"", ""'"", ""'Qt"", ""'"", ""'SQL"", ...",90000,175000,Гибкий график,Более 6 лет,Москва,М13,NaN
...,...,...,...,...,...,...,...,...,...,...,...
160557,169773,169773,Начальник отдела развития и поддержки разработ...,"['Qt', 'C++', 'POSIX']",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
160558,169774,169774,Системный программист (Aurora TEE),"['ARM', 'ARM', 'assembler', 'ARM', 'TrustZone']",35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа,NaN
160559,169776,169776,Руководитель команды системных компонентов UI,"['RPM', 'open', 'source', 'Sailfish', 'OS', 'A...",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа,NaN
160560,169777,169777,Разработчик C++ Qt,['QT'],35000,90000,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец,NaN
160561,169778,169778,Аналитик 1С: УХ (казначейство),"['–', '–']",35000,90000,Полный день,От 1 года до 3 лет,Москва,СИГМА,NaN

In [69]:
not_empty_clear = not_empty.drop(columns=['index', 'Unnamed: 0'])
not_empty_clear

,Unnamed: 0.1,Название вакансии,Ключевые навыки,Начальная зарплата,Конечная зарплата,График работы,Требуемый опыт,Город,Работодатель
0,0,Стажер-инженер по тестированию,"[""'hardskils"", ""'""]",40000,95000,Сменный график,Нет опыта,Москва,Лаборатория Касперского
1,1,Разработчик приложений (Qt/Qml),"[""'Sailfish"", ""'"", ""'OS"", ""'"", ""'Qt"", ""'"", ""'V...",25000,85000,Сменный график,От 3 до 6 лет,Москва,Открытая мобильная платформа
2,2,Системный аналитик (UX),"[""'Sailfish"", ""'"", ""'Ubuntu"", ""'"", ""'Touch"", ""...",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа
3,3,Системный программист С/С++ (разработка ОС Авр...,"[""'Linux"", ""'"", ""'Linux"", ""'"", ""'++"", ""'""]",35000,90000,Полный день,От 1 года до 3 лет,Москва,Открытая мобильная платформа
4,4,С++/Qt разработчик (Senior),"[""'Qt"", ""'"", ""'QML"", ""'"", ""'Qt"", ""'"", ""'SQL"", ...",90000,175000,Гибкий график,Более 6 лет,Москва,М13
...,...,...,...,...,...,...,...,...,...
160557,169773,Начальник отдела развития и поддержки разработ...,"['Qt', 'C++', 'POSIX']",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа
160558,169774,Системный программист (Aurora TEE),"['ARM', 'ARM', 'assembler', 'ARM', 'TrustZone']",35000,90000,Полный день,От 3 до 6 лет,Москва,Открытая мобильная платформа
160559,169776,Руководитель команды системных компонентов UI,"['RPM', 'open', 'source', 'Sailfish', 'OS', 'A...",35000,90000,Полный день,Более 6 лет,Москва,Открытая мобильная платформа
160560,169777,Разработчик C++ Qt,['QT'],35000,90000,Гибкий график,От 3 до 6 лет,Москва,Фирма Светец
160561,169778,Аналитик 1С: УХ (казначейство),"['–', '–']",35000,90000,Полный день,От 1 года до 3 лет,Москва,СИГМА

In [70]:
not_empty_clear.to_excel('clear_data_with_skills.xlsx', index=False)

## Выделение ключевых навыков с помощью предобработки данных

In [71]:
import pandas as pd

# Чтение данных из файла Excel
df = pd.read_excel("clear_tokenized_dataframe.xlsx")

# Создание пустого словаря для подсчета встречаемости навыков
skills_count = {}

# Итерация по каждой строке в столбце "Ключевые навыки"
for skills_list in df['Ключевые навыки']:
    # Преобразование строки списка навыков в фактический список
    skills = eval(skills_list)
    # Подсчет встречаемости каждого навыка
    for skill in skills:
        if skill in skills_count:
            skills_count[skill] += 1
        else:
            skills_count[skill] = 1

# Создание DataFrame из словаря с навыками и их частотой
skills_df = pd.DataFrame(list(skills_count.items()), columns=['Навык', 'Частота'])

# Сортировка DataFrame по частоте встречаемости навыков
skills_df = skills_df.sort_values(by='Частота', ascending=False)

# Сохранение DataFrame в файл Excel
skills_df.to_excel("top_skills.xlsx", index=False)

In [72]:
# Загрузка данных из Excel
df = pd.read_excel("top_skills.xlsx")

# Замена символьных значений на пустую строку
df['Навык'] = df['Навык'].str.replace('[^a-zA-Z0-9 ]', '', regex=True)

# Пересохранение данных обратно в Excel
df.to_excel('top_skills_new.xlsx', index=False)